% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ADS503 Final Project},
  pdfauthor={Saloni Barhate and Jordan Torres},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ADS503 Final Project}
\author{Saloni Barhate and Jordan Torres}
\date{2025-06-22}

\begin{document}
\maketitle

\subsection{Data preprocessing}\label{data-preprocessing}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Library Imports for Knit }
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.1
## v ggplot2   3.5.2     v tibble    3.2.1
## v lubridate 1.9.4     v tidyr     1.3.1
## v purrr     1.0.4     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(corrplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## corrplot 0.95 loaded
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load dataset with NA encoded as \textquotesingle{}?\textquotesingle{}}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"/Users/Jordan/Documents/USD/Summer 2025/Final 503/ADS\_503\_Final\_SB/heart+disease/processed.cleveland.data"}\NormalTok{,}
\AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{na.strings =} \StringTok{"?"}\NormalTok{)}

\CommentTok{\# Assign column names based on UCI documentation}
\FunctionTok{colnames}\NormalTok{(df) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"age"}\NormalTok{, }\StringTok{"sex"}\NormalTok{, }\StringTok{"cp"}\NormalTok{, }\StringTok{"trestbps"}\NormalTok{, }\StringTok{"chol"}\NormalTok{, }\StringTok{"fbs"}\NormalTok{, }\StringTok{"restecg"}\NormalTok{,}
                  \StringTok{"thalach"}\NormalTok{, }\StringTok{"exang"}\NormalTok{, }\StringTok{"oldpeak"}\NormalTok{, }\StringTok{"slope"}\NormalTok{, }\StringTok{"ca"}\NormalTok{, }\StringTok{"thal"}\NormalTok{, }\StringTok{"target"}\NormalTok{)}
\FunctionTok{str}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    303 obs. of  14 variables:
##  $ age     : num  63 67 67 37 41 56 62 57 63 53 ...
##  $ sex     : num  1 1 1 1 0 1 0 0 1 1 ...
##  $ cp      : num  1 4 4 3 2 2 4 4 4 4 ...
##  $ trestbps: num  145 160 120 130 130 120 140 120 130 140 ...
##  $ chol    : num  233 286 229 250 204 236 268 354 254 203 ...
##  $ fbs     : num  1 0 0 0 0 0 0 0 0 1 ...
##  $ restecg : num  2 2 2 0 2 0 2 0 2 2 ...
##  $ thalach : num  150 108 129 187 172 178 160 163 147 155 ...
##  $ exang   : num  0 1 1 0 0 0 0 1 0 1 ...
##  $ oldpeak : num  2.3 1.5 2.6 3.5 1.4 0.8 3.6 0.6 1.4 3.1 ...
##  $ slope   : num  3 2 2 3 1 1 3 1 2 3 ...
##  $ ca      : num  0 3 2 0 0 0 2 0 1 0 ...
##  $ thal    : num  6 3 7 3 3 3 3 3 7 7 ...
##  $ target  : int  0 2 1 0 0 0 3 0 2 1 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age             sex               cp           trestbps    
##  Min.   :29.00   Min.   :0.0000   Min.   :1.000   Min.   : 94.0  
##  1st Qu.:48.00   1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:120.0  
##  Median :56.00   Median :1.0000   Median :3.000   Median :130.0  
##  Mean   :54.44   Mean   :0.6799   Mean   :3.158   Mean   :131.7  
##  3rd Qu.:61.00   3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:140.0  
##  Max.   :77.00   Max.   :1.0000   Max.   :4.000   Max.   :200.0  
##                                                                  
##       chol            fbs            restecg          thalach     
##  Min.   :126.0   Min.   :0.0000   Min.   :0.0000   Min.   : 71.0  
##  1st Qu.:211.0   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:133.5  
##  Median :241.0   Median :0.0000   Median :1.0000   Median :153.0  
##  Mean   :246.7   Mean   :0.1485   Mean   :0.9901   Mean   :149.6  
##  3rd Qu.:275.0   3rd Qu.:0.0000   3rd Qu.:2.0000   3rd Qu.:166.0  
##  Max.   :564.0   Max.   :1.0000   Max.   :2.0000   Max.   :202.0  
##                                                                   
##      exang           oldpeak         slope             ca        
##  Min.   :0.0000   Min.   :0.00   Min.   :1.000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.00   1st Qu.:1.000   1st Qu.:0.0000  
##  Median :0.0000   Median :0.80   Median :2.000   Median :0.0000  
##  Mean   :0.3267   Mean   :1.04   Mean   :1.601   Mean   :0.6722  
##  3rd Qu.:1.0000   3rd Qu.:1.60   3rd Qu.:2.000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :6.20   Max.   :3.000   Max.   :3.0000  
##                                                  NA's   :4       
##       thal           target      
##  Min.   :3.000   Min.   :0.0000  
##  1st Qu.:3.000   1st Qu.:0.0000  
##  Median :3.000   Median :0.0000  
##  Mean   :4.734   Mean   :0.9373  
##  3rd Qu.:7.000   3rd Qu.:2.0000  
##  Max.   :7.000   Max.   :4.0000  
##  NA's   :2
\end{verbatim}

\subsection{A histogram to see the distribution of age
column}\label{a-histogram-to-see-the-distribution-of-age-column}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =} \DecValTok{5}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Distribution of Age"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Age"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-2-1.pdf}}

\subsection{The mean, median and mode of age column - median is red,
mode is blue, mean is
green}\label{the-mean-median-and-mode-of-age-column---median-is-red-mode-is-blue-mean-is-green}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate stats}
\NormalTok{mean\_age }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{age)}
\NormalTok{median\_age }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{age)}
\NormalTok{mode\_age }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{names}\NormalTok{(}\FunctionTok{sort}\NormalTok{(}\FunctionTok{table}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{age), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{))[}\DecValTok{1}\NormalTok{])  }\CommentTok{\# get mode}

\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =} \DecValTok{5}\NormalTok{, }\AttributeTok{fill =} \StringTok{"gray80"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =}\NormalTok{ mean\_age), }\AttributeTok{color =} \StringTok{"green"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =}\NormalTok{ median\_age), }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =}\NormalTok{ mode\_age), }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Age Distribution with Mean, Median, and Mode"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Age"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## i Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-3-1.pdf}}

\section{Error getting the sex value to load, so we are loading the data
again to get the sex column
loaded}\label{error-getting-the-sex-value-to-load-so-we-are-loading-the-data-again-to-get-the-sex-column-loaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Re{-}import only the sex column from the file}
\NormalTok{df\_raw }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"/Users/Jordan/Documents/USD/Summer 2025/Final 503/ADS\_503\_Final\_SB/heart+disease/processed.cleveland.data"}\NormalTok{,}
                   \AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{na.strings =} \StringTok{"?"}\NormalTok{)}

\CommentTok{\# Replace just the sex column}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{sex }\OtherTok{\textless{}{-}}\NormalTok{ df\_raw[[}\DecValTok{2}\NormalTok{]]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check values}
\FunctionTok{unique}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{sex)  }\CommentTok{\# Should show 0 and 1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Convert to factor with labels}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{sex }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{sex, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Female"}\NormalTok{, }\StringTok{"Male"}\NormalTok{))}

\CommentTok{\# Confirm it\textquotesingle{}s working}
\FunctionTok{table}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Female   Male 
##     97    206
\end{verbatim}

\section{Histogram of age column and coloring by
sex}\label{histogram-of-age-column-and-coloring-by-sex}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{fill =}\NormalTok{ sex)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =} \DecValTok{5}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Age Distribution by Sex"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Age"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Count"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Sex"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-6-1.pdf}}
This histogram of patient age by sex revealed a close to normal
distribution centered between 50 and 60 years. Male participants (n =
206) comprised the majority of the sample, with female participants (n =
97) making up a smaller proportion. Across all age groups, males
outnumbered females. However, the distribution pattern was similar for
both sexes, with the highest frequency occurring in the 55--60 age
range. This demographic skew may influence model training outcomes.

\subsection{Let's explore cp (Chest Pain)
column}\label{lets-explore-cp-chest-pain-column}

\section{From the dataset website we know that CP is chest pain
type}\label{from-the-dataset-website-we-know-that-cp-is-chest-pain-type}

\begin{verbatim}
    -- Value 1: typical angina
    -- Value 2: atypical angina
    -- Value 3: non-anginal pain
    -- Value 4: asymptomatic
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df}\SpecialCharTok{$}\NormalTok{cp }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{cp,}
                \AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{),}
                \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Typical angina "}\NormalTok{, }\StringTok{"Atypical angina"}\NormalTok{, }\StringTok{"Non{-}anginal"}\NormalTok{, }\StringTok{"Asymptomatic"}\NormalTok{))}
\FunctionTok{table}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{cp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Typical angina  Atypical angina     Non-anginal    Asymptomatic 
##               0              23              50              86
\end{verbatim}

In the dataset, no participants reported experiencing typical angina.
The majority of individuals were classified as having asymptomatic chest
pain (n = 86), followed by non-anginal pain (n = 50), and atypical
angina (n = 23). This distribution suggests that the dataset is heavily
skewed toward cases with less classic chest pain presentations.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# visually explore how chest pain type relates to heart disease diagnosis}
\CommentTok{\# Drop NAs in cp before plotting}
\NormalTok{df\_cp }\OtherTok{\textless{}{-}}\NormalTok{ df[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{cp), ]}

\CommentTok{\# Plot with improved formatting}
\FunctionTok{ggplot}\NormalTok{(df\_cp, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ cp, }\AttributeTok{fill =} \FunctionTok{factor}\NormalTok{(target))) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"fill"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proportion of Heart Disease by Chest Pain Type"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Chest Pain Type"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Proportion"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Diagnosis Level"}\NormalTok{) }\SpecialCharTok{+} \CommentTok{\#num or Target = diagnosis of heart disease}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_brewer}\NormalTok{(}\AttributeTok{palette =} \StringTok{"Set2"}\NormalTok{)  }\CommentTok{\# optional: nicer colors}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-8-1.pdf}}
\#\# Explore the resting blood pressure (trestbps) column

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{trestbps }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, ]  }\CommentTok{\# remove invalid BP values}
\FunctionTok{summary}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{trestbps)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    94.0   120.0   130.0   131.7   140.0   200.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Histogram of the trestbps column}
\FunctionTok{ggplot}\NormalTok{(df\_clean, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ trestbps)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =} \DecValTok{5}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Distribution of Resting Blood Pressure (trestbps)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Resting Blood Pressure (mm Hg)"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Count"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-10-1.pdf}}
This histogram of resting blood pressure values (trestbps) revealed a
distribution centered around 130 mm Hg, with most patients falling
between 120 and 140 mm Hg. The mean resting blood pressure was 131.7 mm
Hg, slightly above the clinical norm of 120 mm Hg. A small number of
physiologically invalid entries (0 mm Hg) were removed from the
analysis. The right-skewed distribution suggests elevated blood pressure
in the sample, which aligns with the known association between
hypertension and increased cardiovascular risk.

\subsubsection{Handle Missing Data}\label{handle-missing-data}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Count of missing values per column}
\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(df))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      age      sex       cp trestbps     chol      fbs  restecg  thalach 
##        0        0      144        0        0        0        0        0 
##    exang  oldpeak    slope       ca     thal   target 
##        0        0        0        4        2        0
\end{verbatim}

\subsubsection{New dataframe for cleaning
data}\label{new-dataframe-for-cleaning-data}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create a copy of the original dataframe}
\NormalTok{df\_model }\OtherTok{\textless{}{-}}\NormalTok{ df}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identify numeric columns EXCEPT \textquotesingle{}target\textquotesingle{}}
\NormalTok{numeric\_cols }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(df\_model)[}\FunctionTok{sapply}\NormalTok{(df\_model, is.numeric) }\SpecialCharTok{\&} \FunctionTok{names}\NormalTok{(df\_model) }\SpecialCharTok{!=} \StringTok{"target"}\NormalTok{]}

\CommentTok{\# Convert target to numeric}
\NormalTok{df\_model}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{as.character}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{target))}

\CommentTok{\# Scale numeric variables (excluding \textquotesingle{}target\textquotesingle{})}
\NormalTok{df\_model[numeric\_cols] }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(df\_model[numeric\_cols])}

\CommentTok{\# View structure and summary}
\FunctionTok{str}\NormalTok{(df\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    303 obs. of  14 variables:
##  $ age     : num  0.947 1.39 1.39 -1.929 -1.487 ...
##  $ sex     : Factor w/ 2 levels "Female","Male": 2 2 2 2 1 2 1 1 2 2 ...
##  $ cp      : Factor w/ 4 levels "Typical angina ",..: 2 NA NA 4 3 3 NA NA NA NA ...
##  $ trestbps: num  0.756 1.609 -0.664 -0.096 -0.096 ...
##  $ chol    : num  -0.2645 0.7592 -0.3417 0.0639 -0.8246 ...
##  $ fbs     : num  2.39 -0.417 -0.417 -0.417 -0.417 ...
##  $ restecg : num  1.015 1.015 1.015 -0.995 1.015 ...
##  $ thalach : num  0.0172 -1.8189 -0.9009 1.6347 0.9789 ...
##  $ exang   : num  -0.695 1.433 1.433 -0.695 -0.695 ...
##  $ oldpeak : num  1.086 0.397 1.344 2.119 0.31 ...
##  $ slope   : num  2.271 0.648 0.648 2.271 -0.975 ...
##  $ ca      : num  -0.717 2.483 1.416 -0.717 -0.717 ...
##  $ thal    : num  0.653 -0.894 1.168 -0.894 -0.894 ...
##  $ target  : num  0 2 1 0 0 0 3 0 2 1 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(df\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age              sex                    cp         trestbps       
##  Min.   :-2.8145   Female: 97   Typical angina :  0   Min.   :-2.14149  
##  1st Qu.:-0.7124   Male  :206   Atypical angina: 23   1st Qu.:-0.66420  
##  Median : 0.1727                Non-anginal    : 50   Median :-0.09601  
##  Mean   : 0.0000                Asymptomatic   : 86   Mean   : 0.00000  
##  3rd Qu.: 0.7259                NA's           :144   3rd Qu.: 0.47218  
##  Max.   : 2.4961                                      Max.   : 3.88132  
##                                                                         
##       chol              fbs             restecg             thalach       
##  Min.   :-2.3310   Min.   :-0.4169   Min.   :-0.995103   Min.   :-3.4364  
##  1st Qu.:-0.6894   1st Qu.:-0.4169   1st Qu.:-0.995103   1st Qu.:-0.7041  
##  Median :-0.1100   Median :-0.4169   Median : 0.009951   Median : 0.1483  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.000000   Mean   : 0.0000  
##  3rd Qu.: 0.5467   3rd Qu.:-0.4169   3rd Qu.: 1.015005   3rd Qu.: 0.7166  
##  Max.   : 6.1283   Max.   : 2.3905   Max.   : 1.015005   Max.   : 2.2904  
##                                                                           
##      exang            oldpeak            slope               ca         
##  Min.   :-0.6955   Min.   :-0.8954   Min.   :-0.9747   Min.   :-0.7171  
##  1st Qu.:-0.6955   1st Qu.:-0.8954   1st Qu.:-0.9747   1st Qu.:-0.7171  
##  Median :-0.6955   Median :-0.2064   Median : 0.6480   Median :-0.7171  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000  
##  3rd Qu.: 1.4331   3rd Qu.: 0.4827   3rd Qu.: 0.6480   3rd Qu.: 0.3496  
##  Max.   : 1.4331   Max.   : 4.4445   Max.   : 2.2708   Max.   : 2.4831  
##                                                        NA's   :4        
##       thal             target      
##  Min.   :-0.8941   Min.   :0.0000  
##  1st Qu.:-0.8941   1st Qu.:0.0000  
##  Median :-0.8941   Median :0.0000  
##  Mean   : 0.0000   Mean   :0.9373  
##  3rd Qu.: 1.1681   3rd Qu.:2.0000  
##  Max.   : 1.1681   Max.   :4.0000  
##  NA's   :2
\end{verbatim}

\subsubsection{Since cp has 144 missing values out of 303
(\textasciitilde47.5\%), we are going to impute cp using mode. This may
have some bias toward the most frequent
class.}\label{since-cp-has-144-missing-values-out-of-303-47.5-we-are-going-to-impute-cp-using-mode.-this-may-have-some-bias-toward-the-most-frequent-class.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Define mode imputation function}
\NormalTok{impute\_mode }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  ux }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(x[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(x)])}
\NormalTok{  ux[}\FunctionTok{which.max}\NormalTok{(}\FunctionTok{tabulate}\NormalTok{(}\FunctionTok{match}\NormalTok{(x, ux)))]}
\NormalTok{\}}
 
\CommentTok{\# Precompute mode for each column }
\NormalTok{cp\_mode   }\OtherTok{\textless{}{-}} \FunctionTok{impute\_mode}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{cp)}
\NormalTok{ca\_mode   }\OtherTok{\textless{}{-}} \FunctionTok{impute\_mode}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{ca)}
\NormalTok{thal\_mode }\OtherTok{\textless{}{-}} \FunctionTok{impute\_mode}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{thal)}

\CommentTok{\# Apply mode imputation}
\NormalTok{df\_model}\SpecialCharTok{$}\NormalTok{cp   }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{cp), cp\_mode, df\_model}\SpecialCharTok{$}\NormalTok{cp)}
\NormalTok{df\_model}\SpecialCharTok{$}\NormalTok{ca   }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{ca), ca\_mode, df\_model}\SpecialCharTok{$}\NormalTok{ca)}
\NormalTok{df\_model}\SpecialCharTok{$}\NormalTok{thal }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{thal), thal\_mode, df\_model}\SpecialCharTok{$}\NormalTok{thal)}

\CommentTok{\# Count missing values per column}
\FunctionTok{sapply}\NormalTok{(df\_model, }\ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(x)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      age      sex       cp trestbps     chol      fbs  restecg  thalach 
##        0        0        0        0        0        0        0        0 
##    exang  oldpeak    slope       ca     thal   target 
##        0        0        0        0        0        0
\end{verbatim}

\subsubsection{Binarizing the target variable for
classification}\label{binarizing-the-target-variable-for-classification}

In order to make this work, we needed to exclude `target'. The original
code would transform target into a Z scale score and would not be able
to be converted into binary.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Binarize the \textquotesingle{}target\textquotesingle{} variable: 0 = No Disease, 1–4 = Disease}

\CommentTok{\# Convert \textquotesingle{}target\textquotesingle{} to numeric if needed}
\NormalTok{df\_model}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{as.character}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{target))}

\CommentTok{\# Binarize target: 0 = No Disease, 1–4 = Disease}
\NormalTok{df\_model}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{target }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}

\CommentTok{\# Convert to factor with labels}
\NormalTok{df\_model}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{),}
                          \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}

\CommentTok{\# Confirm results}
\FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{target))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## No_Disease    Disease 
##        164        139
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Normalize numerical features}
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'caret'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     lift
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identify numeric columns to scale}
\NormalTok{num\_vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"age"}\NormalTok{, }\StringTok{"trestbps"}\NormalTok{, }\StringTok{"chol"}\NormalTok{, }\StringTok{"thalach"}\NormalTok{, }\StringTok{"oldpeak"}\NormalTok{)}

\CommentTok{\# Apply standardization (z{-}score normalization)}
\NormalTok{preproc }\OtherTok{\textless{}{-}} \FunctionTok{preProcess}\NormalTok{(df\_model[, num\_vars], }\AttributeTok{method =} \FunctionTok{c}\NormalTok{(}\StringTok{"center"}\NormalTok{, }\StringTok{"scale"}\NormalTok{))}
\NormalTok{df\_model[, num\_vars] }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(preproc, df\_model[, num\_vars])}

\CommentTok{\# Confirm structure and summary}
\FunctionTok{str}\NormalTok{(df\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    303 obs. of  14 variables:
##  $ age     : num  0.947 1.39 1.39 -1.929 -1.487 ...
##  $ sex     : Factor w/ 2 levels "Female","Male": 2 2 2 2 1 2 1 1 2 2 ...
##  $ cp      : int  2 4 4 4 3 3 4 4 4 4 ...
##  $ trestbps: num  0.756 1.609 -0.664 -0.096 -0.096 ...
##  $ chol    : num  -0.2645 0.7592 -0.3417 0.0639 -0.8246 ...
##  $ fbs     : num  2.39 -0.417 -0.417 -0.417 -0.417 ...
##  $ restecg : num  1.015 1.015 1.015 -0.995 1.015 ...
##  $ thalach : num  0.0172 -1.8189 -0.9009 1.6347 0.9789 ...
##  $ exang   : num  -0.695 1.433 1.433 -0.695 -0.695 ...
##  $ oldpeak : num  1.086 0.397 1.344 2.119 0.31 ...
##  $ slope   : num  2.271 0.648 0.648 2.271 -0.975 ...
##  $ ca      : num  -0.717 2.483 1.416 -0.717 -0.717 ...
##  $ thal    : num  0.653 -0.894 1.168 -0.894 -0.894 ...
##  $ target  : Factor w/ 2 levels "No_Disease","Disease": 1 2 2 1 1 1 2 1 2 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(df\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age              sex            cp           trestbps       
##  Min.   :-2.8145   Female: 97   Min.   :2.000   Min.   :-2.14149  
##  1st Qu.:-0.7124   Male  :206   1st Qu.:4.000   1st Qu.:-0.66420  
##  Median : 0.1727                Median :4.000   Median :-0.09601  
##  Mean   : 0.0000                Mean   :3.683   Mean   : 0.00000  
##  3rd Qu.: 0.7259                3rd Qu.:4.000   3rd Qu.: 0.47218  
##  Max.   : 2.4961                Max.   :4.000   Max.   : 3.88132  
##       chol              fbs             restecg             thalach       
##  Min.   :-2.3310   Min.   :-0.4169   Min.   :-0.995103   Min.   :-3.4364  
##  1st Qu.:-0.6894   1st Qu.:-0.4169   1st Qu.:-0.995103   1st Qu.:-0.7041  
##  Median :-0.1100   Median :-0.4169   Median : 0.009951   Median : 0.1483  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.000000   Mean   : 0.0000  
##  3rd Qu.: 0.5467   3rd Qu.:-0.4169   3rd Qu.: 1.015005   3rd Qu.: 0.7166  
##  Max.   : 6.1283   Max.   : 2.3905   Max.   : 1.015005   Max.   : 2.2904  
##      exang            oldpeak            slope               ca           
##  Min.   :-0.6955   Min.   :-0.8954   Min.   :-0.9747   Min.   :-0.717104  
##  1st Qu.:-0.6955   1st Qu.:-0.8954   1st Qu.:-0.9747   1st Qu.:-0.717104  
##  Median :-0.6955   Median :-0.2064   Median : 0.6480   Median :-0.717104  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000   Mean   :-0.009467  
##  3rd Qu.: 1.4331   3rd Qu.: 0.4827   3rd Qu.: 0.6480   3rd Qu.: 0.349633  
##  Max.   : 1.4331   Max.   : 4.4445   Max.   : 2.2708   Max.   : 2.483107  
##       thal                  target   
##  Min.   :-0.894063   No_Disease:164  
##  1st Qu.:-0.894063   Disease   :139  
##  Median :-0.894063                   
##  Mean   :-0.005901                   
##  3rd Qu.: 1.168105                   
##  Max.   : 1.168105
\end{verbatim}

\subsection{Exploratory Data Analysis (EDA) Post
Clean}\label{exploratory-data-analysis-eda-post-clean}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(df\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age              sex            cp           trestbps       
##  Min.   :-2.8145   Female: 97   Min.   :2.000   Min.   :-2.14149  
##  1st Qu.:-0.7124   Male  :206   1st Qu.:4.000   1st Qu.:-0.66420  
##  Median : 0.1727                Median :4.000   Median :-0.09601  
##  Mean   : 0.0000                Mean   :3.683   Mean   : 0.00000  
##  3rd Qu.: 0.7259                3rd Qu.:4.000   3rd Qu.: 0.47218  
##  Max.   : 2.4961                Max.   :4.000   Max.   : 3.88132  
##       chol              fbs             restecg             thalach       
##  Min.   :-2.3310   Min.   :-0.4169   Min.   :-0.995103   Min.   :-3.4364  
##  1st Qu.:-0.6894   1st Qu.:-0.4169   1st Qu.:-0.995103   1st Qu.:-0.7041  
##  Median :-0.1100   Median :-0.4169   Median : 0.009951   Median : 0.1483  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.000000   Mean   : 0.0000  
##  3rd Qu.: 0.5467   3rd Qu.:-0.4169   3rd Qu.: 1.015005   3rd Qu.: 0.7166  
##  Max.   : 6.1283   Max.   : 2.3905   Max.   : 1.015005   Max.   : 2.2904  
##      exang            oldpeak            slope               ca           
##  Min.   :-0.6955   Min.   :-0.8954   Min.   :-0.9747   Min.   :-0.717104  
##  1st Qu.:-0.6955   1st Qu.:-0.8954   1st Qu.:-0.9747   1st Qu.:-0.717104  
##  Median :-0.6955   Median :-0.2064   Median : 0.6480   Median :-0.717104  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000   Mean   :-0.009467  
##  3rd Qu.: 1.4331   3rd Qu.: 0.4827   3rd Qu.: 0.6480   3rd Qu.: 0.349633  
##  Max.   : 1.4331   Max.   : 4.4445   Max.   : 2.2708   Max.   : 2.483107  
##       thal                  target   
##  Min.   :-0.894063   No_Disease:164  
##  1st Qu.:-0.894063   Disease   :139  
##  Median :-0.894063                   
##  Mean   :-0.005901                   
##  3rd Qu.: 1.168105                   
##  Max.   : 1.168105
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(df\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    303 obs. of  14 variables:
##  $ age     : num  0.947 1.39 1.39 -1.929 -1.487 ...
##  $ sex     : Factor w/ 2 levels "Female","Male": 2 2 2 2 1 2 1 1 2 2 ...
##  $ cp      : int  2 4 4 4 3 3 4 4 4 4 ...
##  $ trestbps: num  0.756 1.609 -0.664 -0.096 -0.096 ...
##  $ chol    : num  -0.2645 0.7592 -0.3417 0.0639 -0.8246 ...
##  $ fbs     : num  2.39 -0.417 -0.417 -0.417 -0.417 ...
##  $ restecg : num  1.015 1.015 1.015 -0.995 1.015 ...
##  $ thalach : num  0.0172 -1.8189 -0.9009 1.6347 0.9789 ...
##  $ exang   : num  -0.695 1.433 1.433 -0.695 -0.695 ...
##  $ oldpeak : num  1.086 0.397 1.344 2.119 0.31 ...
##  $ slope   : num  2.271 0.648 0.648 2.271 -0.975 ...
##  $ ca      : num  -0.717 2.483 1.416 -0.717 -0.717 ...
##  $ thal    : num  0.653 -0.894 1.168 -0.894 -0.894 ...
##  $ target  : Factor w/ 2 levels "No_Disease","Disease": 1 2 2 1 1 1 2 1 2 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Missing values visualization}
\FunctionTok{library}\NormalTok{(VIM)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: colorspace
\end{verbatim}

\begin{verbatim}
## Loading required package: grid
\end{verbatim}

\begin{verbatim}
## VIM is ready to use.
\end{verbatim}

\begin{verbatim}
## Suggestions and bug-reports can be submitted at: https://github.com/statistikat/VIM/issues
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'VIM'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:datasets':
## 
##     sleep
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{aggr}\NormalTok{(df\_model, }\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}navyblue\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{), }\AttributeTok{numbers=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sortVars=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-18-1.pdf}}

\begin{verbatim}
## 
##  Variables sorted by number of missings: 
##  Variable Count
##       age     0
##       sex     0
##        cp     0
##  trestbps     0
##      chol     0
##       fbs     0
##   restecg     0
##   thalach     0
##     exang     0
##   oldpeak     0
##     slope     0
##        ca     0
##      thal     0
##    target     0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Distribution of key numeric variables}
\FunctionTok{ggplot}\NormalTok{(df\_model, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{fill =} \StringTok{"steelblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Age Distribution"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Age"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-19-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df\_model, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ chol)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{fill =} \StringTok{"darkgreen"}\NormalTok{, }\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Cholesterol Distribution"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Cholesterol"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-19-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df\_model, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ thalach)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{fill =} \StringTok{"purple"}\NormalTok{, }\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Max Heart Rate Distribution"}\NormalTok{, }\AttributeTok{x =} \StringTok{"thalach"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-19-3.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Target variable distribution}
\FunctionTok{table}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{target)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## No_Disease    Disease 
##        164        139
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df\_model, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{factor}\NormalTok{(target))) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{fill =} \StringTok{"coral"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Heart Disease Outcome Distribution"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Target (0 = No, 1 = Yes)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-19-4.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Boxplots of numeric variables by target}
\FunctionTok{ggplot}\NormalTok{(df\_model, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{factor}\NormalTok{(target), }\AttributeTok{y =}\NormalTok{ age)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Age by Heart Disease Status"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Target"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Age"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-19-5.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df\_model, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{factor}\NormalTok{(target), }\AttributeTok{y =}\NormalTok{ thalach)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \StringTok{"lightpink"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Max Heart Rate by Heart Disease Status"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Target"}\NormalTok{, }\AttributeTok{y =} \StringTok{"thalach"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-19-6.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Correlation heatmap of numeric variables}
\NormalTok{numeric\_vars }\OtherTok{\textless{}{-}}\NormalTok{ df\_model }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select\_if}\NormalTok{(is.numeric)}

\NormalTok{cor\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(numeric\_vars, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\FunctionTok{corrplot}\NormalTok{(cor\_matrix, }\AttributeTok{method =} \StringTok{"color"}\NormalTok{, }\AttributeTok{type =} \StringTok{"upper"}\NormalTok{, }\AttributeTok{tl.cex =} \FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-19-7.pdf}}

\subsection{Train/Test Split and Model Building - Waiting to look over
with changed
dataset}\label{traintest-split-and-model-building---waiting-to-look-over-with-changed-dataset}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required library}
\FunctionTok{library}\NormalTok{(caret)}

\CommentTok{\# Identify the numeric predictor columns (excluding target)}
\NormalTok{numeric\_cols }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(df\_model)[}\FunctionTok{sapply}\NormalTok{(df\_model, is.numeric) }\SpecialCharTok{\&} \FunctionTok{names}\NormalTok{(df\_model) }\SpecialCharTok{!=} \StringTok{"target"}\NormalTok{]}

\CommentTok{\# Stratified Train/Test Split }
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{train\_index }\OtherTok{\textless{}{-}} \FunctionTok{createDataPartition}\NormalTok{(df\_model}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{p =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{list =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{train }\OtherTok{\textless{}{-}}\NormalTok{ df\_model[train\_index, ]}
\NormalTok{test }\OtherTok{\textless{}{-}}\NormalTok{ df\_model[}\SpecialCharTok{{-}}\NormalTok{train\_index, ]}

\CommentTok{\# Standardize numeric predictors using preProcess on training data only}
\NormalTok{preproc }\OtherTok{\textless{}{-}} \FunctionTok{preProcess}\NormalTok{(train[, numeric\_cols], }\AttributeTok{method =} \FunctionTok{c}\NormalTok{(}\StringTok{"center"}\NormalTok{, }\StringTok{"scale"}\NormalTok{))}

\CommentTok{\# Apply to both sets}
\NormalTok{train[, numeric\_cols] }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(preproc, train[, numeric\_cols])}
\NormalTok{test[, numeric\_cols]  }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(preproc, test[, numeric\_cols])}

\CommentTok{\# Confirm stratified target distribution}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Training set class distribution:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Training set class distribution:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(train}\SpecialCharTok{$}\NormalTok{target)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## No_Disease    Disease 
##  0.5399061  0.4600939
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Testing set class distribution:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Testing set class distribution:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## No_Disease    Disease 
##  0.5444444  0.4555556
\end{verbatim}

\subsection{Machine Learning}\label{machine-learning}

This dataset contains a mix of categorical, integer, and real-valued
features describing patient demographics and clinical test results.
Because our goal is to predict whether a patient has heart disease (a
binary classification task), we selected a range of supervised
classification models. These include logistic regression, decision
trees, random forests, support vector machines, k-nearest neighbors, and
gradient boosting.

\subsubsection{Logisitc regression
model}\label{logisitc-regression-model}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Logistic Regression Model (Binary Classification)}

\CommentTok{\# Fit the logistic regression model}
\NormalTok{log\_model }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(target }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train, }\AttributeTok{family =}\NormalTok{ binomial)}

\CommentTok{\# Predict probabilities on the test set}
\NormalTok{log\_probs }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(log\_model, }\AttributeTok{newdata =}\NormalTok{ test, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}

\CommentTok{\# Convert probabilities to binary class predictions (threshold = 0.5)}
\NormalTok{log\_preds }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(log\_probs }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{, }\StringTok{"Disease"}\NormalTok{, }\StringTok{"No\_Disease"}\NormalTok{)}

\CommentTok{\# Convert predictions and actuals to factors with consistent levels}
\NormalTok{log\_preds }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(log\_preds, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}
\NormalTok{actual    }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}

\CommentTok{\# Generate confusion matrix}
\FunctionTok{confusionMatrix}\NormalTok{(log\_preds, actual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Reference
## Prediction   No_Disease Disease
##   No_Disease         42       7
##   Disease             7      34
##                                           
##                Accuracy : 0.8444          
##                  95% CI : (0.7528, 0.9123)
##     No Information Rate : 0.5444          
##     P-Value [Acc > NIR] : 1.629e-09       
##                                           
##                   Kappa : 0.6864          
##                                           
##  Mcnemar's Test P-Value : 1               
##                                           
##             Sensitivity : 0.8571          
##             Specificity : 0.8293          
##          Pos Pred Value : 0.8571          
##          Neg Pred Value : 0.8293          
##              Prevalence : 0.5444          
##          Detection Rate : 0.4667          
##    Detection Prevalence : 0.5444          
##       Balanced Accuracy : 0.8432          
##                                           
##        'Positive' Class : No_Disease      
## 
\end{verbatim}

The logistic regression model was trained to predict the presence of
heart disease using clinical and demographic predictors. The model
achieved an overall accuracy of 84.44\%, significantly above the
no-information rate of 54.44\% (p \textless{} .001). Sensitivity was
85.71\%, indicating strong performance in correctly identifying
individuals without heart disease. Specificity was 82.93\%, suggesting
good classification of those with disease. The balanced accuracy was
84.32\%, and Cohen's kappa was 0.686, reflecting substantial agreement
beyond chance.

\subsubsection{Decision tree model}\label{decision-tree-model}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#\# Decision Tree Model}

\CommentTok{\# Load required package}
\FunctionTok{library}\NormalTok{(rpart)}

\CommentTok{\# Fit decision tree model using the training data}
\NormalTok{tree\_model }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(target }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train, }\AttributeTok{method =} \StringTok{"class"}\NormalTok{)}

\CommentTok{\# Predict class labels on test data}
\NormalTok{tree\_preds }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(tree\_model, }\AttributeTok{newdata =}\NormalTok{ test, }\AttributeTok{type =} \StringTok{"class"}\NormalTok{)}

\CommentTok{\# Convert predictions and actual labels to factors with matching levels}
\NormalTok{tree\_preds }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(tree\_preds, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}
\NormalTok{actual     }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}

\CommentTok{\# Evaluate model performance}
\FunctionTok{confusionMatrix}\NormalTok{(tree\_preds, actual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Reference
## Prediction   No_Disease Disease
##   No_Disease         41      18
##   Disease             8      23
##                                          
##                Accuracy : 0.7111         
##                  95% CI : (0.606, 0.8018)
##     No Information Rate : 0.5444         
##     P-Value [Acc > NIR] : 0.0008961      
##                                          
##                   Kappa : 0.4058         
##                                          
##  Mcnemar's Test P-Value : 0.0775562      
##                                          
##             Sensitivity : 0.8367         
##             Specificity : 0.5610         
##          Pos Pred Value : 0.6949         
##          Neg Pred Value : 0.7419         
##              Prevalence : 0.5444         
##          Detection Rate : 0.4556         
##    Detection Prevalence : 0.6556         
##       Balanced Accuracy : 0.6989         
##                                          
##        'Positive' Class : No_Disease     
## 
\end{verbatim}

The classification model achieved an overall accuracy of 71.11\% (95\%
CI: 60.6\%--80.2\%), significantly higher than the no-information rate
of 54.44\%, p \textless{} .001. Sensitivity was strong at 83.67\%,
correctly identifying most patients without heart disease. However,
specificity was lower (56.10\%), suggesting reduced performance in
identifying those with the condition. The model's balanced accuracy was
69.89\%, and Cohen's kappa indicated moderate agreement beyond chance (k
= 0.41).

\subsubsection{Random Forest Model}\label{random-forest-model}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load package}
\FunctionTok{library}\NormalTok{(randomForest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## randomForest 4.7-1.2
\end{verbatim}

\begin{verbatim}
## Type rfNews() to see new features/changes/bug fixes.
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'randomForest'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     combine
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:ggplot2':
## 
##     margin
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Train Random Forest}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)  }\CommentTok{\# for reproducibility}
\NormalTok{rf\_model }\OtherTok{\textless{}{-}} \FunctionTok{randomForest}\NormalTok{(target }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train, }\AttributeTok{ntree =} \DecValTok{100}\NormalTok{, }\AttributeTok{importance =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Predict class labels on the test set}
\NormalTok{rf\_preds }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(rf\_model, }\AttributeTok{newdata =}\NormalTok{ test)}

\CommentTok{\# Ensure predicted and actual values are factors with consistent levels}
\NormalTok{rf\_preds }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(rf\_preds, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}
\NormalTok{actual   }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}

\CommentTok{\# Evaluate model performance}
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{confusionMatrix}\NormalTok{(rf\_preds, actual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Reference
## Prediction   No_Disease Disease
##   No_Disease         43      11
##   Disease             6      30
##                                           
##                Accuracy : 0.8111          
##                  95% CI : (0.7149, 0.8859)
##     No Information Rate : 0.5444          
##     P-Value [Acc > NIR] : 1.061e-07       
##                                           
##                   Kappa : 0.6154          
##                                           
##  Mcnemar's Test P-Value : 0.332           
##                                           
##             Sensitivity : 0.8776          
##             Specificity : 0.7317          
##          Pos Pred Value : 0.7963          
##          Neg Pred Value : 0.8333          
##              Prevalence : 0.5444          
##          Detection Rate : 0.4778          
##    Detection Prevalence : 0.6000          
##       Balanced Accuracy : 0.8046          
##                                           
##        'Positive' Class : No_Disease      
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot variable importance}
\FunctionTok{varImpPlot}\NormalTok{(rf\_model)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-23-1.pdf}}

The random forest model achieved an accuracy of 81.11\% (95\% CI:
71.5\%--88.6\%), significantly outperforming the no-information rate of
54.44\% (p \textless{} .001). Sensitivity was high (87.76\%), indicating
strong performance in identifying patients without heart disease, while
specificity was 73.17\%, showing reasonable ability to detect those with
the condition. The model's balanced accuracy was 80.46\%, and Cohen's
kappa (k = 0.62) suggested substantial agreement beyond chance. Variable
importance analysis indicated that maximum heart rate (thalach),
thalassemia status (thal), and number of colored vessels (ca) were the
most influential features in prediction.

\subsubsection{Support Vector Machine}\label{support-vector-machine}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load necessary libraries}
\FunctionTok{library}\NormalTok{(e1071)}
\FunctionTok{library}\NormalTok{(caret)}

\CommentTok{\# Reuse preprocessed data (df\_model) and stratified split (train/test)}
\CommentTok{\# Confirm target is factor (should already be, but good check)}
\NormalTok{train}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}
\NormalTok{test}\SpecialCharTok{$}\NormalTok{target  }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}

\CommentTok{\# Ensure numeric features are scaled — already done with preProcess() earlier}

\CommentTok{\# Train linear SVM}
\NormalTok{svm\_model }\OtherTok{\textless{}{-}} \FunctionTok{svm}\NormalTok{(target }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train, }\AttributeTok{kernel =} \StringTok{"linear"}\NormalTok{, }\AttributeTok{probability =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Predict class labels}
\NormalTok{svm\_preds }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(svm\_model, }\AttributeTok{newdata =}\NormalTok{ test)}

\CommentTok{\# Align factor levels}
\NormalTok{svm\_preds }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(svm\_preds, }\AttributeTok{levels =} \FunctionTok{levels}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target))}
\NormalTok{test\_target }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{levels}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target))}

\CommentTok{\# Ensure lengths match}
\FunctionTok{stopifnot}\NormalTok{(}\FunctionTok{length}\NormalTok{(svm\_preds) }\SpecialCharTok{==} \FunctionTok{length}\NormalTok{(test\_target))}

\CommentTok{\# Evaluate performance}
\FunctionTok{confusionMatrix}\NormalTok{(svm\_preds, test\_target)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Reference
## Prediction   No_Disease Disease
##   No_Disease         42       8
##   Disease             7      33
##                                         
##                Accuracy : 0.8333        
##                  95% CI : (0.74, 0.9036)
##     No Information Rate : 0.5444        
##     P-Value [Acc > NIR] : 7.067e-09     
##                                         
##                   Kappa : 0.6633        
##                                         
##  Mcnemar's Test P-Value : 1             
##                                         
##             Sensitivity : 0.8571        
##             Specificity : 0.8049        
##          Pos Pred Value : 0.8400        
##          Neg Pred Value : 0.8250        
##              Prevalence : 0.5444        
##          Detection Rate : 0.4667        
##    Detection Prevalence : 0.5556        
##       Balanced Accuracy : 0.8310        
##                                         
##        'Positive' Class : No_Disease    
## 
\end{verbatim}

The support vector machine (SVM) model achieved an accuracy of 83.33\%
(95\% CI: 74.0\%--90.4\%), significantly higher than the no-information
rate of 54.44\% (p \textless{} .001). Sensitivity and specificity were
85.71\% and 80.49\%, respectively, indicating that the model performed
well in detecting both the absence and presence of heart disease. The
balanced accuracy was 83.10\%, and Cohen's kappa (k = 0.66) demonstrated
substantial agreement beyond chance.

\subsubsection{k-Nearest Neighbours}\label{k-nearest-neighbours}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required libraries}
\FunctionTok{library}\NormalTok{(class)}
\FunctionTok{library}\NormalTok{(caret)}

\CommentTok{\# Prepare predictor matrices (drop \textquotesingle{}target\textquotesingle{} column)}
\NormalTok{train\_x }\OtherTok{\textless{}{-}}\NormalTok{ train[, }\FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(train), }\StringTok{"target"}\NormalTok{)]}
\NormalTok{test\_x  }\OtherTok{\textless{}{-}}\NormalTok{ test[, }\FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(test), }\StringTok{"target"}\NormalTok{)]}

\CommentTok{\# Convert predictors to numeric (required for distance calculation)}
\NormalTok{train\_x }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(train\_x, as.numeric))}
\NormalTok{test\_x  }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(test\_x, as.numeric))}

\CommentTok{\# Extract target vectors and ensure consistent factor levels}
\NormalTok{train\_y }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}
\NormalTok{test\_y  }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"No\_Disease"}\NormalTok{, }\StringTok{"Disease"}\NormalTok{))}

\CommentTok{\# Run k{-}NN classifier (k = 5)}
\NormalTok{knn\_preds }\OtherTok{\textless{}{-}} \FunctionTok{knn}\NormalTok{(}\AttributeTok{train =}\NormalTok{ train\_x, }\AttributeTok{test =}\NormalTok{ test\_x, }\AttributeTok{cl =}\NormalTok{ train\_y, }\AttributeTok{k =} \DecValTok{5}\NormalTok{)}

\CommentTok{\# Evaluate performance}
\FunctionTok{confusionMatrix}\NormalTok{(knn\_preds, test\_y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Reference
## Prediction   No_Disease Disease
##   No_Disease         44       8
##   Disease             5      33
##                                           
##                Accuracy : 0.8556          
##                  95% CI : (0.7657, 0.9208)
##     No Information Rate : 0.5444          
##     P-Value [Acc > NIR] : 3.463e-10       
##                                           
##                   Kappa : 0.7071          
##                                           
##  Mcnemar's Test P-Value : 0.5791          
##                                           
##             Sensitivity : 0.8980          
##             Specificity : 0.8049          
##          Pos Pred Value : 0.8462          
##          Neg Pred Value : 0.8684          
##              Prevalence : 0.5444          
##          Detection Rate : 0.4889          
##    Detection Prevalence : 0.5778          
##       Balanced Accuracy : 0.8514          
##                                           
##        'Positive' Class : No_Disease      
## 
\end{verbatim}

The k-nearest neighbors (k-NN) with k = 5 model achieved the highest
overall accuracy of 85.56\% (95\% CI: 76.6\%--92.1\%) across all models
tested, significantly exceeding the no-information rate of 54.44\% (p
\textless{} .001). The model showed excellent sensitivity (89.80\%) and
strong specificity (80.49\%), with a balanced accuracy of 85.14\%.
Cohen's kappa (k = 0.71) indicated substantial agreement beyond chance,
suggesting robust overall model performance.

\subsubsection{Gradient Boosting Machine
(GBM)}\label{gradient-boosting-machine-gbm}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required packages}
\FunctionTok{library}\NormalTok{(gbm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loaded gbm 2.2.2
\end{verbatim}

\begin{verbatim}
## This version of gbm is no longer under development. Consider transitioning to gbm3, https://github.com/gbm-developers/gbm3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}

\CommentTok{\# Use the same preprocessed train/test split}
\NormalTok{train\_gbm }\OtherTok{\textless{}{-}}\NormalTok{ train}
\NormalTok{test\_gbm  }\OtherTok{\textless{}{-}}\NormalTok{ test}

\CommentTok{\# Convert target to binary numeric: 0 = No\_Disease, 1 = Disease}
\NormalTok{train\_gbm}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(train\_gbm}\SpecialCharTok{$}\NormalTok{target }\SpecialCharTok{==} \StringTok{"Disease"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{test\_gbm}\SpecialCharTok{$}\NormalTok{target  }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(test\_gbm}\SpecialCharTok{$}\NormalTok{target }\SpecialCharTok{==} \StringTok{"Disease"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\CommentTok{\# Train GBM model}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{gbm\_model }\OtherTok{\textless{}{-}} \FunctionTok{gbm}\NormalTok{(}
  \AttributeTok{formula =}\NormalTok{ target }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .,}
  \AttributeTok{data =}\NormalTok{ train\_gbm,}
  \AttributeTok{distribution =} \StringTok{"bernoulli"}\NormalTok{,}
  \AttributeTok{n.trees =} \DecValTok{100}\NormalTok{,}
  \AttributeTok{interaction.depth =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{cv.folds =} \DecValTok{5}\NormalTok{,}
  \AttributeTok{verbose =} \ConstantTok{FALSE}
\NormalTok{)}

\CommentTok{\# Predict probabilities on the test set}
\NormalTok{gbm\_probs }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(gbm\_model, }\AttributeTok{newdata =}\NormalTok{ test\_gbm, }\AttributeTok{n.trees =} \DecValTok{100}\NormalTok{, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}

\CommentTok{\# Convert probabilities to class predictions (threshold = 0.5)}
\NormalTok{gbm\_preds }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(gbm\_probs }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\CommentTok{\# Convert to factor with correct levels}
\NormalTok{gbm\_preds }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(gbm\_preds, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{actual    }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_gbm}\SpecialCharTok{$}\NormalTok{target, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}

\CommentTok{\# Evaluate performance}
\FunctionTok{confusionMatrix}\NormalTok{(gbm\_preds, actual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction  0  1
##          0 41  8
##          1  8 33
##                                           
##                Accuracy : 0.8222          
##                  95% CI : (0.7274, 0.8948)
##     No Information Rate : 0.5444          
##     P-Value [Acc > NIR] : 2.84e-08        
##                                           
##                   Kappa : 0.6416          
##                                           
##  Mcnemar's Test P-Value : 1               
##                                           
##             Sensitivity : 0.8367          
##             Specificity : 0.8049          
##          Pos Pred Value : 0.8367          
##          Neg Pred Value : 0.8049          
##              Prevalence : 0.5444          
##          Detection Rate : 0.4556          
##    Detection Prevalence : 0.5444          
##       Balanced Accuracy : 0.8208          
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

The gradient boosting machine (GBM) classifier was trained to detect the
presence of heart disease using 100 trees and a depth of 3. The model
achieved an accuracy of 82.22\% (95\% CI: 72.7\%--89.5\%), significantly
outperforming the no-information rate of 54.44\% (p \textless{} .001).
The model demonstrated strong sensitivity (83.67\%) and specificity
(80.49\%), resulting in a balanced accuracy of 82.08\%. Cohen's kappa (k
= 0.64) indicated substantial agreement beyond chance.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#\# Final Model Comparison Table}

\FunctionTok{library}\NormalTok{(knitr)}

\NormalTok{model\_comparison }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}\StringTok{"k{-}NN (k = 5)"}\NormalTok{, }\StringTok{"Logistic Regression"}\NormalTok{, }\StringTok{"SVM (Linear)"}\NormalTok{, }\StringTok{"GBM"}\NormalTok{, }\StringTok{"Random Forest"}\NormalTok{, }\StringTok{"Decision Tree"}\NormalTok{),}
  \AttributeTok{Accuracy =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.8556}\NormalTok{, }\FloatTok{0.8444}\NormalTok{, }\FloatTok{0.8333}\NormalTok{, }\FloatTok{0.8222}\NormalTok{, }\FloatTok{0.8111}\NormalTok{, }\FloatTok{0.7111}\NormalTok{),}
  \AttributeTok{Balanced\_Accuracy =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.8514}\NormalTok{, }\FloatTok{0.8432}\NormalTok{, }\FloatTok{0.8310}\NormalTok{, }\FloatTok{0.8208}\NormalTok{, }\FloatTok{0.8046}\NormalTok{, }\FloatTok{0.6989}\NormalTok{),}
  \AttributeTok{Kappa =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.7071}\NormalTok{, }\FloatTok{0.6864}\NormalTok{, }\FloatTok{0.6633}\NormalTok{, }\FloatTok{0.6416}\NormalTok{, }\FloatTok{0.6154}\NormalTok{, }\FloatTok{0.4058}\NormalTok{),}
  \AttributeTok{Sensitivity =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.8980}\NormalTok{, }\FloatTok{0.8571}\NormalTok{, }\FloatTok{0.8571}\NormalTok{, }\FloatTok{0.8367}\NormalTok{, }\FloatTok{0.8776}\NormalTok{, }\FloatTok{0.8367}\NormalTok{),}
  \AttributeTok{Specificity =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.8049}\NormalTok{, }\FloatTok{0.8293}\NormalTok{, }\FloatTok{0.8049}\NormalTok{, }\FloatTok{0.8049}\NormalTok{, }\FloatTok{0.7317}\NormalTok{, }\FloatTok{0.5610}\NormalTok{)}
\NormalTok{)}

\FunctionTok{kable}\NormalTok{(model\_comparison, }\AttributeTok{caption =} \StringTok{"Comparison of Model Performance Metrics"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2564}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1154}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2308}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0897}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1538}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1538}}@{}}
\caption{Comparison of Model Performance Metrics}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Accuracy
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Balanced\_Accuracy
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Kappa
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Sensitivity
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Specificity
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Accuracy
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Balanced\_Accuracy
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Kappa
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Sensitivity
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Specificity
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
k-NN (k = 5) & 0.8556 & 0.8514 & 0.7071 & 0.8980 & 0.8049 \\
Logistic Regression & 0.8444 & 0.8432 & 0.6864 & 0.8571 & 0.8293 \\
SVM (Linear) & 0.8333 & 0.8310 & 0.6633 & 0.8571 & 0.8049 \\
GBM & 0.8222 & 0.8208 & 0.6416 & 0.8367 & 0.8049 \\
Random Forest & 0.8111 & 0.8046 & 0.6154 & 0.8776 & 0.7317 \\
Decision Tree & 0.7111 & 0.6989 & 0.4058 & 0.8367 & 0.5610 \\
\end{longtable}

Across all models tested, the k-nearest neighbors (k-NN) classifier with
k = 5 demonstrated the best overall performance, achieving the highest
accuracy (85.56\%) and balanced accuracy (85.14\%) among the models.
Logistic regression and SVM also performed very well, offering strong
interpretability alongside robust predictive power. Ensemble methods
such as GBM and Random Forest yielded stable results, particularly in
detecting non-disease cases, though they did not outperform the simpler
models. Decision trees showed the weakest specificity, limiting their
reliability in clinical settings. Ultimately, the k-NN model offers an
excellent balance of sensitivity and specificity, making it a strong
candidate for early heart disease risk classification in this dataset.

\subsection{Apply Hyperparameter
Tuning}\label{apply-hyperparameter-tuning}

To improve model performance, hyperparameter tuning will be performed on
the top-performing models (k-NN and Logistic Regression). This process
aims to determine whether optimized parameters can lead to improved
accuracy and overall model metrics.

\subsubsection{Tuning k for k-NN}\label{tuning-k-for-k-nn}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required libraries}
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{library}\NormalTok{(class)}

\CommentTok{\# Prepare the data (already preprocessed, scaled, and cleaned)}
\NormalTok{train\_y }\OtherTok{\textless{}{-}}\NormalTok{ train}\SpecialCharTok{$}\NormalTok{target}
\NormalTok{test\_y }\OtherTok{\textless{}{-}}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{target}

\CommentTok{\# Convert predictors to numeric}
\NormalTok{train\_x }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(train[, }\FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(train), }\StringTok{"target"}\NormalTok{)], as.numeric))}
\NormalTok{test\_x }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(test[, }\FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(test), }\StringTok{"target"}\NormalTok{)], as.numeric))}

\CommentTok{\# Combine for caret::train}
\NormalTok{train\_data }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(train\_x, }\AttributeTok{target =}\NormalTok{ train\_y)}

\CommentTok{\# Set up cross{-}validation}
\NormalTok{ctrl }\OtherTok{\textless{}{-}} \FunctionTok{trainControl}\NormalTok{(}\AttributeTok{method =} \StringTok{"cv"}\NormalTok{, }\AttributeTok{number =} \DecValTok{10}\NormalTok{, }\AttributeTok{classProbs =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Define grid of k values (odd to avoid ties)}
\NormalTok{knn\_grid }\OtherTok{\textless{}{-}} \FunctionTok{expand.grid}\NormalTok{(}\AttributeTok{k =} \FunctionTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{25}\NormalTok{, }\AttributeTok{by =} \DecValTok{2}\NormalTok{))}

\CommentTok{\# Train model using caret}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{knn\_tuned }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(}
\NormalTok{  target }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .,}
  \AttributeTok{data =}\NormalTok{ train\_data,}
  \AttributeTok{method =} \StringTok{"knn"}\NormalTok{,}
  \AttributeTok{trControl =}\NormalTok{ ctrl,}
  \AttributeTok{tuneGrid =}\NormalTok{ knn\_grid,}
  \AttributeTok{metric =} \StringTok{"Accuracy"}  \CommentTok{\# Or use "Kappa" or "ROC" if classProbs=TRUE}
\NormalTok{)}

\CommentTok{\# Plot results}
\FunctionTok{plot}\NormalTok{(knn\_tuned)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ADSD503_Final_files/figure-latex/unnamed-chunk-28-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Evaluate on test set using best k}
\NormalTok{best\_k }\OtherTok{\textless{}{-}}\NormalTok{ knn\_tuned}\SpecialCharTok{$}\NormalTok{bestTune}\SpecialCharTok{$}\NormalTok{k}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Best k:"}\NormalTok{, best\_k, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Best k: 15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knn\_preds }\OtherTok{\textless{}{-}} \FunctionTok{knn}\NormalTok{(}\AttributeTok{train =}\NormalTok{ train\_x, }\AttributeTok{test =}\NormalTok{ test\_x, }\AttributeTok{cl =}\NormalTok{ train\_y, }\AttributeTok{k =}\NormalTok{ best\_k)}
\FunctionTok{confusionMatrix}\NormalTok{(knn\_preds, test\_y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Reference
## Prediction   No_Disease Disease
##   No_Disease         43      12
##   Disease             6      29
##                                           
##                Accuracy : 0.8             
##                  95% CI : (0.7025, 0.8769)
##     No Information Rate : 0.5444          
##     P-Value [Acc > NIR] : 3.697e-07       
##                                           
##                   Kappa : 0.5919          
##                                           
##  Mcnemar's Test P-Value : 0.2386          
##                                           
##             Sensitivity : 0.8776          
##             Specificity : 0.7073          
##          Pos Pred Value : 0.7818          
##          Neg Pred Value : 0.8286          
##              Prevalence : 0.5444          
##          Detection Rate : 0.4778          
##    Detection Prevalence : 0.6111          
##       Balanced Accuracy : 0.7924          
##                                           
##        'Positive' Class : No_Disease      
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# k=15 looked the highest so we are }
\NormalTok{knn\_tuned}\SpecialCharTok{$}\NormalTok{results[knn\_tuned}\SpecialCharTok{$}\NormalTok{results}\SpecialCharTok{$}\NormalTok{k }\SpecialCharTok{==} \DecValTok{15}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    k  Accuracy     Kappa AccuracySD   KappaSD
## 8 15 0.8449567 0.6826376 0.07400544 0.1514844
\end{verbatim}

A grid search was conducted to tune the number of neighbors (k) in the
k-NN model using 10-fold cross-validation. Accuracy peaked at k = 15,
achieving a mean CV accuracy of 84.5\% (SD = 0.074). The tuned model was
then evaluated on the test set, where it achieved 80.0\% accuracy (95\%
CI: 70.3\% -- 87.7\%), with a balanced accuracy of 79.2\%, sensitivity
of 87.8\%, and specificity of 70.7\%. Compared to the untuned model (k =
5, 85.6\% test accuracy), the tuned model provided a more stable
estimate, though at the cost of slightly lower specificity.

\subsubsection{Logistic Regression with
Regularization}\label{logistic-regression-with-regularization}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required libraries}
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{library}\NormalTok{(glmnet)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'Matrix'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:tidyr':
## 
##     expand, pack, unpack
\end{verbatim}

\begin{verbatim}
## Loaded glmnet 4.1-9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Convert factor target to numeric (caret expects numeric for glmnet)}
\NormalTok{train}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(train}\SpecialCharTok{$}\NormalTok{target }\SpecialCharTok{==} \StringTok{"Disease"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{test}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(test}\SpecialCharTok{$}\NormalTok{target }\SpecialCharTok{==} \StringTok{"Disease"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\CommentTok{\# Set up training control}
\NormalTok{ctrl }\OtherTok{\textless{}{-}} \FunctionTok{trainControl}\NormalTok{(}\AttributeTok{method =} \StringTok{"cv"}\NormalTok{, }\AttributeTok{number =} \DecValTok{10}\NormalTok{, }\AttributeTok{classProbs =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{summaryFunction =}\NormalTok{ twoClassSummary)}

\CommentTok{\# Create tuning grid}
\NormalTok{grid }\OtherTok{\textless{}{-}} \FunctionTok{expand.grid}\NormalTok{(}
  \AttributeTok{alpha =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{),       }\CommentTok{\# 0 = ridge, 1 = lasso, 0.5 = elastic net}
  \AttributeTok{lambda =} \DecValTok{10}\SpecialCharTok{\^{}}\FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{length =} \DecValTok{10}\NormalTok{) }\CommentTok{\# Try a wide range of penalties}
\NormalTok{)}

\CommentTok{\# caret needs target as factor with names like "yes"/"no" or "Class1"/"Class2"}
\NormalTok{train\_data }\OtherTok{\textless{}{-}}\NormalTok{ train}
\NormalTok{train\_data}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(train\_data}\SpecialCharTok{$}\NormalTok{target }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\StringTok{"Disease"}\NormalTok{, }\StringTok{"No\_Disease"}\NormalTok{))}

\CommentTok{\# Train model}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{log\_tuned }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(}
\NormalTok{  target }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .,}
  \AttributeTok{data =}\NormalTok{ train\_data,}
  \AttributeTok{method =} \StringTok{"glmnet"}\NormalTok{,}
  \AttributeTok{family =} \StringTok{"binomial"}\NormalTok{,}
  \AttributeTok{tuneGrid =}\NormalTok{ grid,}
  \AttributeTok{metric =} \StringTok{"ROC"}\NormalTok{,  }\CommentTok{\# You can also use "Accuracy"}
  \AttributeTok{trControl =}\NormalTok{ ctrl}
\NormalTok{)}

\CommentTok{\# View the best alpha and lambda}
\FunctionTok{print}\NormalTok{(log\_tuned}\SpecialCharTok{$}\NormalTok{bestTune)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   alpha     lambda
## 5     0 0.01668101
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Predict on test set}
\NormalTok{test\_data }\OtherTok{\textless{}{-}}\NormalTok{ test}
\NormalTok{test\_data}\SpecialCharTok{$}\NormalTok{target }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(test\_data}\SpecialCharTok{$}\NormalTok{target }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\StringTok{"Disease"}\NormalTok{, }\StringTok{"No\_Disease"}\NormalTok{))}

\NormalTok{log\_preds }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(log\_tuned, }\AttributeTok{newdata =}\NormalTok{ test\_data)}
\FunctionTok{confusionMatrix}\NormalTok{(log\_preds, test\_data}\SpecialCharTok{$}\NormalTok{target)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             Reference
## Prediction   Disease No_Disease
##   Disease         34          6
##   No_Disease       7         43
##                                           
##                Accuracy : 0.8556          
##                  95% CI : (0.7657, 0.9208)
##     No Information Rate : 0.5444          
##     P-Value [Acc > NIR] : 3.463e-10       
##                                           
##                   Kappa : 0.7082          
##                                           
##  Mcnemar's Test P-Value : 1               
##                                           
##             Sensitivity : 0.8293          
##             Specificity : 0.8776          
##          Pos Pred Value : 0.8500          
##          Neg Pred Value : 0.8600          
##              Prevalence : 0.4556          
##          Detection Rate : 0.3778          
##    Detection Prevalence : 0.4444          
##       Balanced Accuracy : 0.8534          
##                                           
##        'Positive' Class : Disease         
## 
\end{verbatim}

Among the models tested, the tuned logistic regression model (ridge
regularization with λ = 0.0167) achieved the highest overall test
accuracy at 85.6\% (95\% CI: 76.6\% -- 92.1\%), with a balanced accuracy
of 85.3\%, a sensitivity of 82.9\%, and a specificity of 87.8\%. This
represents a performance gain over the basic logistic regression model,
which had a slightly lower accuracy of 84.4\%, a balanced accuracy of
84.3\%, and a kappa of 0.686, compared to 0.708 for the tuned version.

The default k-NN model (k = 5) matched the tuned logistic regression in
test accuracy at 85.6\%, but showed slightly lower specificity (80.5\%)
and kappa (0.707). After tuning, k-NN with k = 15 achieved 80.0\% (95\%
CI: 70.3\% -- 87.7\%) accuracy, suggesting more stable performance
across cross-validation folds but a modest drop on unseen data. While
both classifiers performed well, the regularized logistic model
ultimately offered the most consistent balance of interpretability,
sensitivity, and specificity, making it well suited for early disease
classification.

\end{document}
